In [37]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler as minmax

array([0.02857143, 0.42857143, 0.62857143, 0.        , 1.        ])

In [ ]:
X = [1.1, 2.5, 3.2, 1.0, 4.5]
newMin = 0
newMax = 1
X_scaled = (X - np.min(X)) / (np.max(X) - np.min(X))* (newMax - newMin) + newMin
X_scaled

In [38]:

minMax = minmax(feature_range=[0,1])
xNew = minMax.fit_transform(np.asanyarray(X).reshape(-1,1))
xNew

array([[0.02857143],
       [0.42857143],
       [0.62857143],
       [0.        ],
       [1.        ]])

In [27]:
import pandas as pd
def EscalamientoDecimal(df):
    for x in df:
        p = df[x].max()
        q = len(str(abs(p)))
        df[x] = df[x]/10**q 
    return df

In [28]:
df = pd.DataFrame([1, 20, 100, 102, 88, 999])
EscalamientoDecimal(df).T

0     1    2      3      4      5
0  0.001  0.02  0.1  0.102  0.088  0.999

In [29]:
from sklearn.preprocessing import StandardScaler
StandardScaler = StandardScaler()
StandardScaler.fit_transform(df)

array([[-0.61862812],
       [-0.5645456 ],
       [-0.33682973],
       [-0.33113683],
       [-0.37098711],
       [ 2.2221274 ]])