In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = np.array([1.1, 2.5, 3.2, 1.0, 4.5])
newMin = 0
newMax = 1

X_scaled = (X - np.min(X)) / (np.max(X) - np.min(X))* (newMax - newMin) + newMin
X_scaled

array([0.02857143, 0.42857143, 0.62857143, 0.        , 1.        ])

In [3]:
minMax = MinMaxScaler(feature_range=[0,1])
xNew = minMax.fit_transform(np.asanyarray(X).reshape(-1,1))
xNew

array([[0.02857143],
       [0.42857143],
       [0.62857143],
       [0.        ],
       [1.        ]])

In [9]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
df = pd.DataFrame([1.1, 2.5, 3.2, 1.0, 4.5])

SS = StandardScaler()
SS.fit_transform(df)

array([[-1.0314877 ],
       [ 0.03033787],
       [ 0.56125066],
       [-1.10733238],
       [ 1.54723154]])

In [ ]:
import pandas as pd
def EscalamientoDecimal(df):
    for x in df:
        p = df[x].max()
        q = len(str(abs(p)))
        df[x] = df[x]/10**q 
    return df

In [ ]:
df = pd.DataFrame([1, 20, 100, 102, 88, 999])
EscalamientoDecimal(df).T